restapi.go
As request by discord developers in `#api-changes`
link https://github.com/bwmarrin/discordgo/issues/13
=> Add DiscordBot user agent

wsapi.go
This also reduces the line count a smidge.
=> Make update status a little more idiomatic.

restapi.go
=> Modifications to GuildBanAdd, closes #29 #33.  Idiomatic improvements to ChannelMessages func.

structs.go, wsapi.go
I also did some minor refactoring to simplify the event handling code which resulted in a delta reduction in lines for this Pull Request.
=> Implement GuildBanAdd/Remove events. Closes #24

wsapi.go
Ok, I have checked and triple checked, I think this is right :dancers:
=> Fix a subtle bug where OnEvent wouldn't get fired for events with state handling.

restapi.go
Also fixes some missing pointer returns.
=> Return an image.Image for user avatars.

message.go, state.go, structs.go, wsapi.go
=> Add support for message state.

restapi.go
Surprised there was no feature request for it!
=> Support sending files.

restapi.go, structs.go
=> Added UserChannelPermissions function

oauth2_test.go, restapi.go, state.go, util.go, voice.go, wsapi.go
=> Changed fmt.Print to log.Print

state.go
=> Don't perform guild lookups if message tracking is not enabled.

state.go, structs.go
Also improve update speed dramatically.
=> Add fast lookups for guilds and channels in state.

state.go
=> Fix potential threading issue.

structs.go
=> Added some fields to ready event

structs.go
Removed muted_channels 
And added:
restricted_guilds (members from these guilds can't direct message you)
allow_email_friend_request
convert_emoticons
friend_source_flags
inline_attachment_media
=> Updated settings struct

message.go
I contribooot 1 line at a time
=> Add mention_roles

restapi.go, restapi_test.go, structs.go
Added the GuildMemberNickname function and the nick field to the guild member struct
One little thing, when changing your own nickname via @me, you have to add "/nick" to the url
=> Nickname support

LICENSE
Sorry about the previous PR. I'm so used to committing to master :)
=> Rename GoDiscord to discordgo in LICENSE (develop)

structs.go
probably gonna be the only one who uses this heh
=> Add guild_positions field to settings

voice.go
=> Update ChannelID in ChangeChannel

restapi.go
It only updates the positions so should maybe be GuildChannelsReorder?
Also apparently does not return any data, even though the docs says so
=> Added GuildChannelsUpdate

discord.go, structs.go, wsapi.go
This implements guild sharding as documented/talked about [here](https://github.com/hammerandchisel/discord-api-docs/issues/17). Unlike the original PR (#166) this isn't garbage and properly defaults/sanitizes the values passed in.
👀  @iopred @bwmarrin
=> Implement guild sharding

endpoints.go, restapi.go, structs.go
=> Added UserGuildSettingsEdit

restapi.go
=> Add function to get a single message by ID

endpoints.go, restapi.go
=> add support for pinning

restapi.go
=> Fix ratelimit mutex with url parameters

events.go, structs.go
Sent when something is pinned/unpinned
=> Added the CHANNEL_PINS_UPDATE event

examples/airhorn/main.go
Close the file when it has been fully loaded
It's just a little enhancement so I didn't open an issue for this one.
=> Close the file after read

restapi.go, structs.go
https://discordapp.com/developers/docs/topics/permissions#role-object
=> Add mentionable to Role struct and update GuildRoleEdit

state.go
In case update was handled before create
=> Apply more fields to existing message in message update

discord.go, restapi.go, structs.go
Will retry up to Session.MaxRestRetries times
=> Retry on 502's

message.go, structs.go, types.go, types_test.go
=> Timestamp type; a string with a Parse() function

message.go, structs.go, types.go, types_test.go
Closes #204
Based on uppfinnarn work
Just replace the Parser pattern by the time pattern of RFC3339
=> Timestamps

events.go, structs.go, wsapi.go
https://discordapp.com/developers/docs/topics/gateway#gateway-request-guild-members
=> Added RequestGuildMembers to request guild members from the gateway

examples/airhorn/README.md, examples/avatar/localfile/README.md, examples/avatar/url/README.md, examples/mytoken/README.md, examples/new_basic/README.md, examples/pingpong/README.md
Updates docs to include the newly required "Bot" infront of bot user tokens.
=> Docs for #247

restapi.go, structs.go
Did you know the Ancient Egyptian word for cat was mau, which means "to see"?
=> Update ChannelMessageAck because of api changes

examples/mytoken/README.md, examples/pingpong/README.md
casing matters for some reason tried BOT and it returns a 401.
Also got the name of the executable wrong in mytoken (damn copy paste...)
=> Fixes a couple of typos

discord.go, endpoints.go, message.go, restapi.go, state.go, structs.go, wsapi.go
@bwmarrin could you take a look? :)
It's working fine in my test bot.
=> Add Webhook support.

ratelimit.go, restapi.go, restapi_test.go
Adds functions to get the amount of members that could be pruned
and to prune members using the prune endpoint.
=> Add support for the prune endpoint

endpoints.go, restapi.go, structs.go
Implements support for the new member role add and delete endpoint
hammerandchisel/discord-api-docs#179
=> Implement support for new member role endpoint

restapi.go, restapi_test.go
=> Updated userguilds to new api

restapi.go, state.go
Account for @everyone overrides in channels.
Simplify both places user permissions are calculated
=> Improve permissions.

discord.go, restapi.go, structs.go
Reusing it has some minor advantages like using cached connections.
=> Reuse http client and export it

restapi.go
Since i missed this for my current project, I thought i'd pr it myself
=> added Around parameter to ChannelMessages (which resolves #293)

restapi.go
UserID and RoleID are minor variables
=> Proper ratelimit buckets for RoleAdd and RoleRemove

ratelimit.go
Instead of a global ratelimit bucket with a mutex, atomically store the unix time in nanoseconds it resets.
Also did some general cleanup in the ratelimit code, the performance is pretty much the same.
=> Replace global ratelimit bucket with atomic

README.md
After I saw this https://github.com/bwmarrin/discordgo/pull/344 I had to fix the headline formating issue
=> Fixed readme headline

user.go
I don't know why somebody would do something this inefficient, but I think plain concatination is a better approach
=> How about no?

events.go
Did this really quickly, tell me if i should change anything.
=> add: MessageReactionRemoveAll event

endpoints.go, eventhandlers.go, events.go, restapi.go
Only added the set endpoint, as that is the only one google told me.
I don't know if you can set them.
Please check if you think I set the correct ratelimiting endpoint.
I was maybe supposed to set it to EndpointUser...
=> Added user notes

message.go, restapi.go
What's a better way of doing this? Reflect? Generator? I'm open to suggestions
=> ChannelFileSendWithComplex

state.go
The presences in the state didn't seem to be updating so I added the methods
`func PresenceAdd`
`func PresenceRemove`
`func Presence`
and the bool
`TrackPresences`
to the State struct
and now update presences on the `PresenceUpdate` event
```go
case *PresenceUpdate:
if s.TrackPresences {
s.PresenceAdd(t.GuildID, &t.Presence)
}
```
I used and adjusted the code suggested from
[Handle PresenceUpdate in state tracking #345](https://github.com/bwmarrin/discordgo/pull/345)
=> Add Presence Tracking to State

restapi.go
For specifying the kick reason
=> Add GuildMemberDeleteWithReason

discord_test.go
Felt like this should be in its own pr instead of jamming it into the gatewaybot one
=> Add bot account to testing

endpoints.go, message.go, state.go, structs.go, wsapi.go
This is untested (except it does compile)
=> Updated to v6 (fixes #408)

structs.go
From https://discordapp.com/developers/docs/topics/response-codes#json-error-response
=> Add error code constants

event.go, state.go
So that you can create your own state and manage it fully on your own.
=> Export State.OnInterface

structs.go
=> Fix #443 (recipients not recipient)

endpoints.go
https://github.com/bwmarrin/discordgo/issues/320
=> Update bulk-delete endpoint

endpoints.go, restapi.go
Well, last time I submitted this I turned it into quite a fiasco by not properly testing, but today I noticed after the revert occurred no additional fix was submitted. This finally fixes #437—fully, properly tested this time. :)
(still sorry about before)
=> Final fix for #437

logging.go
I would like this PR to be merged because I can use it to replace the log what discordgo does with something like logrus.
Feel free to add comments for adjustments that might need to be made.
=> Add support for custom logging behaviour.

restapi.go, structs.go
=> Remove XKCDPass Invites

endpoints.go, restapi.go, structs.go
=> adds GuildAuditLog()

structs.go
Small update to supported Game Activity Types in structs.go:
```go
// GameType is the type of "game" (see GameType* consts) in the Game struct
type GameType int
// Valid GameType values
const (
GameTypeGame GameType = iota
GameTypeStreaming
GameTypeListening // Added
GameTypeWatching  // Added
)
```
=> Small update to supported Game Activity Types

wsapi.go
Quick, simple thing I came across :)
=> Removed unnecessary error check

restapi.go, structs.go
Adds a method to fetch your own connections.
Only works on a user account.
To get another user's connections you would need to fetch their profile while on a user account.
=> Added UserConnections function and structs

event.go, message.go, state.go, structs.go, user.go
I went through most of the major structs and threw some comments in, especially in relation to odd things present in the API which aren't fully reflected in the library. I tried my best to scan for typos, but if I ended up letting one through, oops.
=> General documentation improvements

restapi.go
Add GuildMemberAdd
https://discordapp.com/developers/docs/resources/guild#add-guild-member
=> Add GuildMemberAdd

restapi.go
Close #434
We may need to wait that the official documentation add this new field
=> Add ChannelID to WebhookEdit (#434)

oauth2_test.go
Signed-off-by: Matthew Roseman <mroseman95@gmail.com>
=> fixed small typo in oauth2_test.go

endpoints.go, restapi.go
https://discordapp.com/developers/docs/resources/emoji#create-guild-emoji
https://discordapp.com/developers/docs/resources/emoji#modify-guild-emoji
https://discordapp.com/developers/docs/resources/emoji#delete-guild-emoji
=> adds GuildEmojiCreate, GuildEmojiEdit, and GuildEmojiDelete

restapi.go
Fingers crossed this will reduce the number of questions around this.
=> Add an explicit log and error for when a request is attempted with an unauthorized token that is not a bot token.

user.go
Adds locale to the User struct per #554
=> #554 Added locale to user struct

structs.go
I'd add the ApplicationID, OwnerID and LastPinTimeStamp but I'm doing this in the web editor.
=> Add userlimit to the channel struct

discord.go
Just noticed these while browsing the code.
I fixed some very minor spelling mistakes, that's it.
=> Minor spelling fixes in discord.go

endpoints.go
Same as EndpointEmoji but ends with ".gif" instead of ".png"
=> Add EndpointEmojiAnimated

structs.go
Sent a pull request upstream as well: https://github.com/discordapp/discord-api-docs/pull/653
=> Add ErrCodeUnknownWebhook

eventhandlers.go, events.go
This adds support for the event fired when Webhooks get created, removed, or updated. It is documented here https://discordapp.com/developers/docs/topics/gateway#webhooks-update .
=> add Webhooks Update event

message_test.go
s.StateEnabled variable already set to true above
=> Remove redundant line

structs.go
https://github.com/bwmarrin/discordgo/issues/579
=> Add PermissionManageEmojis and PermissionManageWebhooks to PermissionAll

endpoints.go, structs.go
Based on https://github.com/discordapp/discord-api-docs/pull/960
=> Add premium fields to Guild and Member

voice.go
Fix these issue for good. No workaround needed.
https://github.com/bwmarrin/discordgo/issues/598
https://github.com/bwmarrin/discordgo/issues/668
=> Fix broken IP Discovery in voice UDP connection.

README.md
=> updates discord api invite link

structs.go
https://discordapp.com/developers/docs/resources/channel
=> Add rate limit per user to Channel struct

message.go, restapi.go, structs.go
=> Fix inconsistent TTS casing

discord.go, structs.go, wsapi.go
This exposes the Identify Packet, and adds missing Identify parameters.  This is a proposed solution to #678
=> Expose Identify Packet

events.go, state.go
I needed to get a deleted message from the cache before deleting it from there.
=> add getting deleted message

events.go
I just added a single field to the GuildMembersChunk event type.
=> Added Presences field for GuildMembersChunk

examples/pingpong/main.go
This is #766 again but due to changing the target branch things got messed up
=> Fix typo in comment of PingPong example

logging.go
Changed "consistancy" to "consistency" in logging.go. This is my second attempt at doing a pull request correctly.
=> Changed "consistancy" to "consistency" in logging.go

discord.go, structs.go, util.go
Issue #742 
How to use?
`s.Identify.Intents =  discordgo.IntentsGuilds | discordgo.IntentsGuildMembers`
=> Basic support for Gateway Intents

structs.go
PR #764 added allowed mentions functionality to MessageSend and MessageEdit, this PR also adds it for webhooks.
=> Add AllowedMentions for webhooks

user.go
based on https://discord.com/developers/docs/resources/user
=> chore: add missing fields in User struct

voice.go
=> Added lock to prevent race condition

structs.go
Add missing field "pending" because of discord update (Membership Screening).
=> Add missing field in member struct

restapi.go
Closes #874 
Add Delete All Reactions for Emoji
Deletes all the reactions for a given emoji on a message.
[https://discord.com/developers/docs/resources/channel#delete-all-reactions-for-emoji](https://discord.com/developers/docs/resources/channel#delete-all-reactions-for-emoji)
=> Add MessageReactionsRemove

voice.go
As ext header length isn't always 1, the shift to find the beginning of
the Opus packet must be adjusted dynamically.
=> Fix RTP extended header parsing

endpoints.go
=> Fix EndpointInvite

message.go, message_test.go, structs.go
I added a function to easily get the emojis out of a message and updated the Activity struct to include everything from the documentation.
=> update Activity struct and add emoji functions

structs.go
Guild Member has a Permissions field for interactions
https://discord.com/developers/docs/resources/guild#guild-member-object
=> add Permissions to Member struct

interactions.go, restapi.go
implement 
https://discord.com/developers/docs/interactions/slash-commands#bulk-overwrite-global-application-commands
and
https://discord.com/developers/docs/interactions/slash-commands#bulk-overwrite-guild-application-commands
=> Bulk command overwrite

README.md, docs/GettingStarted.md, docs/index.md, examples/README.md
Changed some things to make docs/index.md look better, including adding periods and changing hyphens to em dashes.
Fixed the link to GettingStarted.md within index.md.
Fixed the images in index.md and README.md.
=> Misc changes to docs

user.go
This pull request adds the Discord Certified Moderator badge flag to the UserFlags class.
PR in discord-api-docs: https://github.com/discord/discord-api-docs/pull/2946
=> Added Certified Moderator badge flag.

user.go
Reverts bwmarrin/discordgo#934
=> Revert "Added Certified Moderator badge flag."

interactions.go
this adds a new struct as shown in the docs
https://discord.com/developers/docs/interactions/slash-commands#interaction-applicationcommandinteractiondataresolved
=> add ApplicationCommandInteractionDataResolved struct

restapi.go
This is useful for getting the ID of the interaction response message which can be used for adding reactions among other things
=> Get webhook message endpoint

structs.go
=> Add ActivityTypeWatching (3)

structs.go
=> feat: add ActivityTypeCompeting (5)

events.go
https://discord.com/developers/docs/topics/gateway#message-reaction-add
=> Add Member to MessageReactionAdd

interactions.go, locales.go
this pr add the new interaction locals see docs and supported locals here
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure
https://discord.com/developers/docs/dispatch/field-values#predefined-field-values-accepted-locales
=> add interaction locales

message.go
This PR
- Adds MessageFlags values.
- Adds comments for each MessageFlags (directly copypasted from discord documentation).
- ~~Uses iota to generate values~~
=> Add MessageFlags values

examples/slash_commands/main.go
Implemented command removing procedure on exit.
=> Removal procedure for slash commands example

structs.go
As you can see. What do you think about adding a ExpiresAt field ?
=> add Invite ExpiresAt field

restapi.go
=> Add support for `with_localizations` flag

restapi.go
=> add GET prefix for ApplicationCommands bucketID

state.go
deleted emoji should be deleted from cache
=> Overwrite entire emoji list on GuildEmojiUpdate

examples/airhorn/README.md, examples/auto_moderation/README.md, examples/autocomplete/README.md, examples/avatar/README.md, examples/components/README.md, examples/context_menus/README.md, examples/dm_pingpong/README.md, examples/modals/README.md, examples/pingpong/README.md, examples/scheduled_events/README.md, examples/slash_commands/README.md, examples/stage_instance/README.md, examples/threads/README.md, examples/voice_receive/README.md
Add README.md to all examples that are missing one.
=> Add README.md to all examples

examples/auto_moderation/main.go, structs.go
Implement https://github.com/discord/discord-api-docs/pull/5504
=> Regex patterns automod rule trigger

examples/airhorn/README.md
Dca-rs does not exist anymore, replaced with the dca cli solution to create .dca
=> chore: replace dca-rs

examples/airhorn/main.go, examples/dm_pingpong/main.go, examples/pingpong/main.go
Resolves #1219 by following the request in #706 to rebase. Since there is no develop branch to pull from, made the merge request on master.
=> removed os.Kill from caught signals in pingpoing, dm_pingpong and airhorn

components.go, examples/components/main.go
Implements https://github.com/discord/discord-api-docs/pull/5543, auto populated (with users, channels and roles) select menus, in `SelectMenu` data structure.
=> Auto populated select menus

interactions.go
this adds a new struct as shown in docs
https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-resolved-object
=> Add MessageComponentInteractionDataResolved struct

interactions.go
Document reference below
https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure
=> Add nsfw option

endpoints.go, structs.go, util.go
Adds guild icon size parameter, guild banner size parameter, missing ClientStatus struct
=> Add size parameters to IconURL and BannerURL

structs.go
Adds the GIF sticker format (https://discord.com/developers/docs/resources/sticker#sticker-object-sticker-format-types)
=> Add GIF sticker format

eventhandlers.go, events.go, structs.go
Implement GUILD_AUDIT_LOG_ENTRY_CREATE gateway event.
The documentation can be found in: https://github.com/discord/discord-api-docs/pull/5849
=> Implement Audit Log Entry Create event

structs.go
=> Fix typo in AuditLogGuildScheduledEventUpdate

structs.go
https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-optional-audit-entry-info
=> feat(auditlog): add integration_type to options

examples/echo/README.md, examples/echo/main.go
Add a simpler example for slash commands.
=> Add echo example

discord_test.go
fixed a small typo on line 252
=> Fixed typo from occured to occurred

structs.go
docs pr: https://github.com/discord/discord-api-docs/pull/6041
https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-events
=> feat(auditlog): add onboarding and server guide actions

events.go, state.go
=> feat(ChannelUpdate): add BeforeUpdate

message.go
https://discord.com/developers/docs/resources/channel#message-object
=> Add poll field to Message struct.

message.go
* Add `Message.MessageSnapshots` field
* Add `MessageSnapshot` type
=> Message Snapshots

structs.go
As stated in #1611, the guild and direct message poll intents are currently missing.
=> feat(structs): add intents for guild and direct message polls

components.go, message.go
Implement components V2 (see [docs](https://discord.com/developers/docs/components/reference#section) for more info)
=> Components V2

eventhandlers.go, events.go, state.go
=> feat: implement GuildStickersUpdate event

message.go
https://discord.com/developers/docs/resources/message#attachment-object
=> feat(MessageAttachment): add Waveform and DurationSecs

message.go
Add `Flags` field to `MessageAttachment` object.
=> feat(MessageAttachment): add flags
