discord.go
state.go
structs.go
wsapi.go

Currently maintains a list of Guilds (Members/Channels) and PrivateChannels.
This allows a lot of nice things like a really easy 'is a message private' check:
```
func (s *Session) IsMessagePrivate(m *Message) bool {
_, err := s.State.GetPrivateChannelByID(m.ID)
return err == nil
}
```
Or a nice check where we grab an invite, and only accept it if we need to.
```
int := "discord.gg/blah"
i, _ := d.Session.Invite(inv)
if _, err := d.Session.State.GetGuildByID(i.Guild.ID); err == nil {
// There was no error, we are already in the guild.
fmt.Println("I have already joined that server.")
return
}
d.Session.InviteAccept(inv)
fmt.Println("I have joined the server.")
```

Implement state tracking.

---

restapi.go

Tested (with $ iptables -A INPUT -s 104.16.59.5 -j DROP )
It works.
Fixes #46

Prevent login crash by assuming a json.Unmarshal "just works"

---

restapi.go

This would fix: https://github.com/bwmarrin/discordgo/issues/49
A first handshake with the Discord API, without having any authentication details would be:
```go
// Register to the Discord server and store the authentication token
dg.Token, err = dg.Register("Username")
if err != nil {
fmt.Println(err)
return
}
// Add authentication information to User
_, err = dg.UserVerify("Username", "myemail@address.com", "Password")
if err != nil {
fmt.Println(err)
return
}
// Login to the Discord Server and store the new authentication token
dg.Token, err = dg.Login("myemail@address.com", "Password")
if err != nil {
fmt.Println(err)
return
}
```
Afterwards it is just like in the api_basic example:
```go
// Login to the Discord Server and store the new authentication token
dg.Token, err = …
```

Register & Verify

---

wsapi.go

The case where a handler is null, if an error happens in marshall, the OnEvent wouldn't fire. Now it will.

Fix subtle difference between events with state tracking and not.

---

discord.go
examples/api_basic/api_basic.go
restapi.go

Eventually we should consider allowing Login/LoginWithToken to mutate
s.Token, it would probably simplify the API a bit.

Add a new optional token to New, which is a cheaper way to login. Closes #89.

---

discord.go
discord_test.go
examples/api_basic/api_basic.go
examples/new_basic/new_basic.go
restapi_test.go
structs.go
wsapi.go

This has a backwards incompatible change to New.
The reason is that with an OnConnect event, there is no time to hook it up, eg:
```
a := discordgo.New()
a.OnConnect = func(s *discordgo.Session){
// Not called.
}
```
Instead, there is now an explicit (and simple) call to start listening, the above example is now:
```
a := discordgo.New()
a.OnConnect = func(s *discordgo.Session){
// Called.
}
a.OpenAndListen()
```

Refactor open/close logic. Support OnConnect and OnDisconnect. Closes #5.

---

discord.go
discord_test.go
events.go
examples/api_basic/api_basic.go
examples/new_basic/new_basic.go
state.go
structs.go
wsapi.go

This change breaks the current API but makes it much more powerful.
Currently only one handler can be added for each event, with this change, any number of handlers can be added for the same event. Additionally it supports adding handlers for interface{} which will be triggered on every event.
The existing code:
```
dg.OnMessageCreate = func(s *discordgo.Session, m *discordgo.Message){
fmt.Println(m.Content)
}
```
is now:
```
dg.AddHandler(func(s *discordgo.Session, m *discordgo.MessageCreate){
fmt.Println(m.Content)
})
```
Not bad for a net delta of -:100: lines.

Mapped Event Handlers

---

endpoints.go
restapi.go

Probably needs some tweaking, something about large_threshold.

Support new GuildMember endpoints.

---

restapi.go
structs.go

Add VerificationLevel value consts and a typedef for int

---

state.go
structs.go
voice.go
wsapi.go

This PR adds support for multiple cross-guild voice connections (one per guild), while also refactoring and cleaning the voice API. This is still a little messy, and could probably do with some love/cleanup before merg'n.
**NB**
1. Previously the library assumed we would get a `VoiceStateUpdate` _before_ a `VoiceServerUpdate`. Because we can't guarantee packets are processed in that order, we now explicitly wait for the VoiceStateUpdate data to be passed into the VoiceServerUpdate. This does create a possible deadlock when initially connecting to voice servers, so it may be advisable to add a timeout condition.
2. Previously the library did _not_ handle VoiceStateUpdate's for other users, causing our internal `State` to get desynced. We now track them, albeit somewhat messily.
3. …

Add the ability to have multiple cross-guild voice connections open.

---

state.go

For any channels that are part of the Guild object given within a GUILD_CREATE packet, discord doesn't send 'guild_id' keys to save space within the WS frame. This means when handling GUILD_CREATE packets for brand new (e.g. untracked) we need to manually set the `guild_id` for every channel.

Fix channels from a GUILD_CREATE packet having null GuildID's

---

state.go
structs.go

We're (Discord) moving to a method of lazy-loading guilds to help with extremely large `READY` packets. With this new method, clients will now receive only the 'id' and 'unavailable' fields for every guild in the `READY` packet, and will lazily receive `GUILD_CREATE` events for those guilds as they are connected by our backend.
Previously discordgo used the Guild objects originally passed in the `READY` payload as the base object for all future events, however with this new method we now case this to when the original guild is not unavailable.
Something this commit does not add, but may be helpful is a way to detect the difference between `GUILD_CREATE`'s used for the handshake process, vs `GUILD_CREATE`'s that actually represent a guild being created/added. Due to the way the state works …

Fix lazy guild loading

---

state.go

Previously we only filled the channelMap inside of READY. Because of lazy guild loading, this was not valid for the majority of users (e.g. bot users and users with more than 100 guilds). We now properly handle both cases, by filling in the channelMap on GUILD_CREATE.
This commit also refactors the way we do locking inside of GUILD_CREATE and CHANNEL_CREATE to be a bit cleaner.
@iopred :eyes: plz

Fix channelMap not being filled for bot users/>100 guilds

---

structs.go
wsapi.go

**Do not merge this until hammerandchisel/discord-api-docs#17 is ready**
This PR adds support for Discords new builtin sharding implementation, which allows users to segment guilds across multiple websocket connections.

Add sharding support

---

restapi.go
structs.go
wsapi.go

Fix unmarshall error with Invite, improve error logging.

---

structs.go
wsapi.go

Reverts bwmarrin/discordgo#166
*cough* *cough* 
discord_test.go:207: DataReady never became true.
Somehow I failed to notice this PR causes discordgo to not work anymore.  @b1naryth1ef 
With this change, dgo goes into a loop trying to connect and gets disconnected and so on, it never makes a connection to the data websocket that can be used.

Revert "Add sharding support"

---

wsapi.go

This adds support for gateway v4 (which we're technically already running; whoops). Really it just moves the version to the URL, and explicitly uses JSON as the encoding. Everything should be supported from previous commits.

Support Gateway v4

---

restapi.go

ChannelMessageAck does not like `application/json` as the content type

Fixed ChannelMessageAck

---

endpoints.go
restapi.go

Added bulk delete endpoint and bulk delete support.

Bulk delete

---

restapi.go

added a new method with the following signature
```
func (s *Session) ChannelFileSendWithMessage(channelID, content string, name string, r io.Reader) (st *Message, err error)
```
to keep backwards compatability i kept the old method but it just calls the full method.

Sendfile enhancement

---

wsapi.go

This removes an unnecessary API call to `/api/users/@me`, which was previously used to check the current user id against the VoiceStateUpdate's user id. However, we have this information from the ready payload stored in state, so lets just use that.
pls stop spam my api @bwmarrin @iopred 
kthx ❤️ 🙈

Remove API call in onVoiceStateUpdate

---

restapi.go
restapi_test.go
structs.go

Recently Discord add the support to change the User status beetween Online, Idle, Do not Distrub and Invisible.
This PR is to implement that new functionality.

Add Support of changing user status

---

restapi.go
structs.go
types.go

Makes it easier to handle errors returned from discord.
This maintain full compatibility with the old error being returned if people are parsing that string.
Not 100% about the names i chose though...

Added custom REST error type

---

endpoints.go
restapi.go

- Adds support for deleting the reaction for a given user.
- Requires MANAGE_MESSAGES permission.
- Fixes the Sesssion.MessageReactions(...) function.

 Fix support for reactions endpoint

---

endpoints.go
events.go
restapi.go
structs.go

Adds Support for:
- Sending friend request.
- Accepting friend request.
- Getting all the relationships.
- Getting all the mutual friends with another user.
- Blocking a user.
**Note:**
- Bot accounts are not allowed to access the endpoint.
- May close bwmarrin/discordgo#150

Add support for relationships

---

restapi.go

I discovered that macOS will fail to resolve the gateway if there isn't a slash in between the domain and the query params.
At some point in time discord removed this trailing slash on the gateway api `https://discordapp.com/api/gateway`
This PR ensures that the gateway always has a trailing slash.
For reference I was getting the following error before `dial tcp: lookup gateway.discord.gg?v=4&encoding=json: no such host`

Fix issue with trailing slashes in MacOS

---

eventhandlers.go
tools/cmd/eventhandlers/main.go

This is just cleanup, little safer, little cleaner.

Generate type assertion code. Don't generate interfaceProviders for internal handlers.

---

event.go
events.go
state.go
wsapi.go

This switch the gateway to V5, and change the heartbeat logic to
get the heartbeat_interval from the new Hello opcode instant of
READY/RESUME event.
See: hammerandchisel/discord-api-docs#18
Fix: #220

Switch to V5 gateway

---

eventhandlers.go
tools/cmd/eventhandlers/main.go

it's done implicitly in the handlerForInterface call.

Remove type checks for handlers.

---

voice.go
wsapi.go

Some locking was incorrect, a lot was missing, i fixed all race conditions i could find using the `-race` detector on different bots.
I have tested shorter voice connections by having a bot connect to voice, play a 2 second long audio file, then disconnect, every 5 seconds for some hours.
Tested longer connections by having a music bot play a track on loop for a couple hours.
This will lower performance a bit, but it's better than to rely on undefined behaviour. 
This pr is probably gonna be annoying to go through with all the new locking, sorry about that.

Fix all found race conditions, and dont send on nil channel

---

endpoints.go

Closes #308 
The addition of cdn endpoints was sort of forced because of the api urls only allowing .jpg.
Would've also added rest/state support for grabbing the group icon that way, but 
1. There's no way of getting the icon hash of a group (nor any sort of handling that is) currently.
2. Not really something i wanted to do originally.
So if anyone else wants to implement gateway v6 and group handling, go ahead.

Use .png for image endpoints and add a few more

---

voice.go
wsapi.go

This was noticeable in stuff like music bots creating a lot of voice connections, more and more cpu will be consumed by the neverending tickers

Fix leaking tickers

---

wsapi.go

Saves the updated channel id when the bot is moved by another user.

Track voice-channel movements in onVoiceStateUpdate()

---

restapi.go

One of the most important thing with this library is that it does 1 request per function. You have 100% control over how many web requests get made.
UserAvatar breaks that.
UserAvatar now accepts a user, which not only makes you know how many web requests gets made, but might also save on web requests if you have an existing user object.

UserAvatar to accept user object.

---

structs.go

When marshalling a user back to JSON, this results in inconsistently cased JSON fields.

Fixed casing for JSON tag for Avatar field on User struct

---

message.go
restapi.go

I was getting tired of all the ChannelMessageSendThisWithThisAndThisAndThis.  
So, well, this is my solution.
I kept the others for compatibility. And `ChannelMessageSend` should always be kept for ease of use.
Anyways, I'm unsure whether I should also include `ChannelFileSend` in this as well. It'd certainly be useful (sending embeds and files together, maybe).  
But that's for later.

ChannelMessageSendComplex

---

message.go
restapi.go

SendContent

---

discord.go
restapi.go
structs.go

This is a re-submit because I accidentaly closed the old pull (See #346)

Arise error when user has 2FA

---

restapi.go

When looking at the docs I noticed this minor error in the documentation.

Fixed grammatical error in restapi.go docs

---

user.go

Simplifies process of tagging a user in messages

add Tag method to user

---

restapi.go

Added reason go GuildBanCreate

---

discord.go

It is called 'Semantic Versioning' and I thought it's a typo worth fixing.

Fix typo in description of VERSION constant

---

structs.go

When this fails decoding, it wouldn't even set the id of the guild for me, thought i was crazy at first when i saw guilds without ids, heh

Fix presence unmarshal with game names as numbers

---

endpoints.go
user.go

Makes obtaining the avatar URL of a user easier.

Methods to obtain a user's avatar URL

---

message.go
restapi.go

(this time with based on develop)
For compatibility with existing library consumers, the File field is retained but will behave as if Files contained that single file. If both are specified, ChannelMessageSendComplex will return an error.
The message JSON payload is moved to a form-data field called `payload_json`, instead of set in multipart form data. This is supported and the recommended way, as per the API docs.
Apparently, you can attach multiple files if you just name the parts names differently in the multipart request. The parts are named here using the order the files were specified, as `file%d`. This is not documented in the API docs, but definitely works.
This also removes serialization of the File field via json.Marshal, as it will never be directly serialized in the JSON. The …

Add and fix support for multiple file uploads via ChannelMessageSendComplex via the new field MessageSend.Files.

---

voice.go

Change's effect on goroutine count growth in our voice heavy bot:

Fix goroutine leak in opusReceiver

---

discord.go
structs.go
wsapi.go

- Error when sending a heartbeat now triggers a reconnection
- Op7 now triggers a reconnection
- Session now tracks the last heartbeat ACK that was recieved. If the
last ACK is more than FailedHeartbeatAcks*heartbeatinterval in the past,
this is treated as a dead connection and a reconnection is forced.

Add heartbeat ACK response and error handling

---

voice.go

runtime.LockOSThread does not do anything for performance and is instead
intended for interfacing with libraries that use thread local data structures.
Closes #402

voice.go: remove runtime.LockOSThread call from opusSender

---

wsapi.go

This is a small change to gracefully handle the possibility of a race condition attempting to reconnect twice, as shown in #406 .

Fix #406: reconnect() can be called while still connected

---

endpoints.go
restapi.go

```go
// MessageReactionsRemoveAll deletes all reactions from a message
// channelID : The channel ID
// messageID : The message ID.
func (s *Session) MessageReactionsRemoveAll(channelID, messageID string) error {
_, err := s.RequestWithBucketID("DELETE", EndpointMessageReactionsAll(channelID, messageID), nil, EndpointMessageReactionsAll(channelID, messageID))
return err
}
```
https://github.com/bwmarrin/discordgo/issues/405

MessageReactionsRemoveAll

---

state.go
wsapi.go

This adds `memberMap` to the State object, in the same vein as the existing `guildMap` and `channelMap`, except it's a map of maps, mapping each guild ID to a map of member IDs paired to members. The map is replaced if necessary in `GuildAdd` so that all the pointers are always up-to-date, and is created in the `OnReady` function.
The Add, Remove, and Get functions have been updated to use the map, but still modify the slice if necessary, so the Member slice is still kept up to date. Speed tests indicate this approach is roughly 4-5 times faster for servers with 500+ members in them.

Add memberMap to State to speed up member queries

---

structs.go

Note: NSFW channels which haven't been modified since the update that introduced this field have it set to `false`.

Add NSFW channel field

---

structs.go
wsapi.go

https://discordapp.com/developers/docs/change-log#august-16-2017-—-breaking-change
While discordgo does always include type there were some other parts they forgot to mention.
I  had to add `omitempty` to Game.Url, and add `afk` and `status` otherwise i would get disconnected from the gateway.
I also changed `idle_since` to `since`,  probably forgot about that in the Gatway 6 update

Fix presence update after breaking API change

---

endpoints.go
restapi.go

When using `Session.CreateGuild`, currently a 404 is returned as `EndpointGuilds` posts to `guilds/` rather than `guilds`, the latter of which is correct according to the Discord API reference. I'm not sure if this is a recent change as the API doesn't show a changelog before v6, but I reproed the issue on my end and this fix seems to work fine.
I originally changed EndpointGuilds to "guild", but didn't really consider that it would break other things (duh), so in this commit I added a new variable, `EndpointGuildCreate`, and used that inside `Session.CreateGuild` instead of `EndpointGuilds`. I threw it down in the more miscellaneous section of the endpoints, as the block with `EndpointGuilds` seemed too general for this variable, while the block with the rest of the guild endpoints was …

Fix for #437 (#2)

---

endpoints.go
restapi.go

Reference Issue: https://github.com/bwmarrin/discordgo/issues/440
This endpoint was declard twice in endpoints.go, and used in the
GuildInvites() method on Session values. I replaced the misspelled
invocation.
All tests pass.

Remove a misspelled copy of EndpointGuildInvites. Issue #440

---

state.go

Adds members from the GuildMembersChunk event to state.
Results in Members being in both, guild.Members + the private members-map compared to just the guild.Members slice when doing it "manually" in your application which can cause issues.

Add members from GuildMembersChunk to state

---

structs.go
wsapi.go

@Ikkerens had his cloned and Rich Presence was implemented on top of this.
- #458 is the original.
- #459 was added as per request.

Implement Raw sending of status (Rich Presence and Online Status)

---

voice.go

Change made to keep the use of logging consistent.

Use v.log rather than log for consistency.

---

structs.go

TimeStamps used in rich presence currently cause the following error:
`[DG0] wsapi.go:477:onEvent() error unmarshalling PRESENCE_UPDATE event, json: cannot unmarshal number 1510183304574.0 into Go struct field TimeStamps.start of type uint`
This change fixes the issue by implementing UnmarshalJSON on TimeStamps and changing startTimestamp and endTimestamp from uint (which may be too small on some platforms) to int64.

Fix TimeStamps unmarshalling (#474)

---

event.go
examples/appmaker/main.go
logging.go
restapi.go
structs.go
voice.go
wsapi.go

Not sure how these remained unfixed for so long, they were all here in plain text with the line numbers: https://goreportcard.com/report/github.com/bwmarrin/discordgo#misspell.

Several typo fixes.

---

structs.go

The unique field can be used to prevent invite reusing.
https://discordapp.com/developers/docs/resources/channel#create-channel-invite
https://discordapp.com/developers/docs/resources/invite#invite-object

Adds the unique field to the invite struct

---

structs.go

This adds the newly added field to the emoji struct identifying animated emojis.

Adds support for animated emojis

---

structs.go

This is essentially a copy of [User.Mention](https://github.com/bwmarrin/discordgo/blob/master/user.go#L26-L29), and is simply a helper function to return a role-mentioning string.

Added Role.Mention function

---

endpoints.go
user.go

AvatarURL will return a link to the default avatars instead of an invalid link if the user has no avatar set.
As described here: https://discordapp.com/developers/docs/reference#image-formatting-cdn-endpoints

adds default avatar generation to AvatarURL method

---

message.go
message_test.go

Roles are mentioned with `<@&number>` instead of `<&number>`

Fix role mention replacement

---

structs.go

This Pull Requests adds some missing fields to the `Guild` struct that can be useful.
They are defined here: https://discordapp.com/developers/docs/resources/guild#guild-object .
It also adds new Types, `ExplicitContentFilterLevel` and `MfaLevel`, which are used by the `Guild` struct.

adds missing fields to guild struct

---

restapi.go

As mentioned in the issue, this will be a breaking change. The old way stopped working however, so this should be a required change.

makes GuildChannelCreate use ChannelType (#510)

---

README.md

from the code I ran on my system with the latest changes this seems to be the syntax for the authentication tokens. I'm guessing it was just never updated.
Let me know if this is incorrect. 
Thanks!

added clarification when initializing discordgo

---

state.go

This fixes #532. Though it's not mentioned on the Discord docs, it seems `Member.JoinedAt` isn't sent in member updates (it *is* sent in member chunks), which caused the value to be overwritten to an empty value after member updates. This pull request changes `State.MemberAdd` to handle each field individually, similarly to other function in the State that have similar dilemmas, checking for an empty `JoinedAt` field.

Changed State.MemberAdd to set fields individually

---

restapi.go

This function currently has an issue where it sends too much data, causing Discord to reject the request as it believes you're trying to amend several fields by sending all of them.
This change resolves that by creating a simplified version of the Channel struct that only sends the data required for reordering.

Reduce data sent to the DAPI in GuildChannelsReorder

---

events.go
message.go
structs.go

Discord has introduced the `guild_id` property into various guild related events and this PR aims to support them.

Add GuildID to Multiple Structs

---

restapi.go
structs.go

This PR implements the optional URL parameter `with_counts` of the Get Invite Request. It returns approximate member counts with the invite object (even for invites of servers the requesting account is not a part of).
It is documented here https://discordapp.com/developers/docs/resources/invite#get-invite

adds InviteWithCounts

---

restapi.go

This Pull Request adds support for the `Unique` field to be sent to Discord when using `ChannelInviteCreate`. This allows for creating many unique invites at once.
Documentation: https://discordapp.com/developers/docs/resources/channel#create-channel-invite

Adds support for the Unique field to ChannelInviteCreate

---

structs.go

.APIName currently covers all REST url cases, but with the introduction of animated Emoji the chat usage of Emoji has become slightly less obvious as well, despite bots being able to use them.
This new func makes usage of custom emoji (including animated ones) easier.

Added .MessageFormat() to emoji struct

---

structs.go

It was previously just string, but has been updated to be consistent with the other structs.

Changed Member.JoinedAt to type Timestamp

---

voice.go

It looks like dgo has moved away from ChannelVoiceLeave ever since discord allows bot to connect to more than one channel. Confusing comment seeing that it is very hard to find information about the function that it mentions.

Update Disconnect() comment

---

structs.go

Associated issue: 
https://github.com/bwmarrin/discordgo/issues/518
I'm not sure if it matters if the member nickname is empty.

Add Member.Mention

---

wsapi.go

The default websocket close handler sends back the close code it received ([see here](https://github.com/gorilla/websocket/blob/23059f29570f0e13fca80ef6aea0f04c11daaa4d/conn.go#L1063-L1070)) .
In some cases, Discord seems to receive that close code. The problem is, if we get a 1000 close code and reply back with a 1000 close code, it'll invalidate our session, and we will not be able to resume it.
Not sending any close code, should do the trick.

Drop the default websocket close handler

---

restapi.go

Copy of #529, because I'm an idiot and deleted the origin branch.
Currently dgo only allows simple creation of channels with just a name and type, this PR adds a "Complex" version of that endpoint, pointing the original method to this new method.

Added GuildChannelCreateComplex

---

structs.go

This PR adds a new field of the Channel object called `rate_limit_per_user`. It can be used to implement a slowmode in a channel.
(I tested the functionality of the field, it works.)
Documentation: https://github.com/discordapp/discord-api-docs/pull/691

Adds rate_limit_per_user to ChannelEdit

---

state.go

Updates member count on GUILD_MEMBER_ADD and GUILD_MEMBER_REMOVE.
**Why this is separate of s.TrackMembers**:
Users do not always want to cache all guild members, but the library should always provide an accurate member count.

track membercount on memberAdd and leave

---

.travis.yml

Older versions of go were making tests fail due to golint.
Post v1.6 of go, golint changed to an official repo.
Error before change:
```
golang.org/x/tools/go/internal/gcimporter
../../../golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
The command "go get -v golang.org/x/lint/golint" failed and exited with 2 during .
```
pre v1.9, this method was not present. 
References:
- https://github.com/golang/go/issues/28291#issuecomment-431568120
- https://github.com/golang/tools/pull/52#issuecomment-432082363

Fixed travis test failing for older versions of go

---

wsapi.go

This PR remove the code duplication between ChannelVoiceJoin and ChannelVoiceJoinManual
The only drawback is that it get signaled twice in the log.
Shoud I put this part in a little private function called by both functions ?

Remove code duplication in ChannelVoiceJoin

---

docs/index.md

Replaces #618 -- originally attempted changing base through GitHub UI, wasn't clean so created a new one.

Update expired Discord API invite link

---

util.go

Returns the creation date of a Snowflake relative to discord. I created a `util.go` file for this function. My next choice would have been putting it in `discord.go`

added SnowflakeTimestamp utility function

---

events.go
state.go

It is currently impossible to obtain a copy of the previous message content when receiving `MessageUpdate`, as the changes are always written to state before the message is sent to the event handler, even when SyncEvents is used.
This PR fixes that by introducing a (shallow) copy of the Message object, allowing comparison of the old and the new message.

Added copy of previous Message state to MessageUpdate

---

restapi.go

The previous documentation stated that the response type was an array of User structures, when the function return an array of GuildBan structures.

Add proper response type for GuildBans docs

---

wsapi.go

As per discordapp/discord-api-docs#967, _trace in OP10 HELLO is no
longer an array of strings, but rather an undefined glob of data that
presently contains a mixed bag of strings and objects.
type helloOp does not seem to be exposed outside of the library, so this
is not a breaking change; furthermore, the Trace field of helloOp was
not used anywhere within the library. It seems like it would be safer to
just remove the field outright, rather than accept it as an interface{}
and waste cycles unmarshaling data that is never used.
This is a critically breaking bug, as if the upstream change is merged,
bots using DiscordGo prior to this patch will be unable to connect; an
error would occur when trying to unmarshal the new data glob into a
[]string, causing (*Session).Open() to prematurely …

fix: remove _trace from helloOp

---

structs.go

There's an `available` field in the JSON data from Discord for custom emojis, even though it's not documented. [Another library has implemented this in their master branch](https://discord.js.org/#/docs/main/master/class/GuildEmoji?scrollTo=available).

Add `Available` field to Emoji struct

---

wsapi.go

Fix #671 by treating an empty channel id passed to ChannelVoiceJoinManual as a nil pointer.

Handle empty channel id in ChannelVoiceJoinManual

---

endpoints.go
oauth2.go

The `/assets` endpoint is used in `https://discordapp.com/developers/applications/$APP_ID/rich-presence/assets` for Rich Presence assets.

Added Asset and ApplicationAssets

---

restapi.go

- Should the API be changed?
- Is the "wait" doc described fine?

Fix #622: support for WebhookExecute msg response

---

endpoints.go
structs.go

Guild Icons can be animated now. 
I added a new Endpoint: `EndpointGuildIconAnimated` 
And the helper `guild.IconURL()`, similar to `user.AvatarURL()`.

 Add EndpointGuildIconAnimated; Add guild.IconURL() helper 

---

restapi.go

Looks like `net/http` strips URL fragments, which causes emoji with `#` in names to be sent incorrectly to some endpoints.
Fixes #614.

Escape # in emoji IDs passed to reaction endpoints

---

structs.go

This resolves #547.
Adds a "LastPinTimestamp" field to the Channel structure, which reflects
the `last_pin_timestamp` field on the Discord API. This field is
indicative of whether or not the channel has any pinned messages, and
can save an API request from being sent if there are none.
FWIW, The API doesn't seem to return a 404 anymore when there are no
pinned messages; it returns a 200 with `[]`.

feature: add last_pin_timestamp to Channel struct

---

go.mod
voice.go

Whenever trying to connect to a voice channel the function never returns.
Use the UDP Endpoint IP from the Ready payload instead of the WebSocket endpoint.
#701 and #702

Fixed holdup issue in voice

---

restapi.go

Fix for Discord's API returning a `400: Bad Request` from empty request body when `Content-Type` header is set.
This PR is associated with issue https://github.com/bwmarrin/discordgo/issues/716

Fix for Discord's API returning a 400 Bad Request from empty request body

---

restapi.go

This keeps Session#Guild a low level method and help it stay consistent with other methods.

Remove State fallback from Session#Guild

---

wsapi.go

This is supported by the Discord API and will save requests.

Support for Batch Request Guild Members

---

go.mod

Updated `structs.go` to support a slice of `[]*Game` which in the json is labeled as `activities`
This is apart of the presence update changes when Custom status released: https://discordapp.com/developers/docs/topics/gateway#presence-update
This resolves #729

Activities Slice and CustomType

---

discord.go

While the existing docs for the `New(...)` function say that the token is used "blindly", and specify that a `Bot ` prefix is necessary for bot tokens, they are not clear that if a single string argument is passed in, it gets passed through to the HTTP Authorization header untouched. They also do not mention the knock-on effect of that, which is that an OAuth2 access token must be prefixed with `Bearer ` when passed into `New(...)` in order to work.
This PR alters the docs to address this issue.

Add clarifying docs for using an OAuth2 token

---

.gitignore
structs.go

Based upon bitwise permissions defined at: https://discordapp.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags
Note: The new `PermissionViewChannel` is technically the same offset as the existing `PermissionReadMessages` permission. However, the Discord documentation doesn't have a specific "READ_MESSAGES" permission, instead using "VIEW_CHANNEL" to govern visibility of both text and voice channels.
To maintain backward compatibility without breaking existing users, `PermissionReadMessages` has been left in because it's an exported const. We may want to somehow mark it as deprecated though.

Add bitwise permission const PermissionViewChannel

---

wsapi.go

Currently, when a reconnection is requested we close the connection with a `1000` close code, on which the API seems to disallow resuming. This is problematic with the recent changes to the API where it requests reconnections much more frequently, and can easily lead to token reset issues on large bots (a re-identify uses one of the 1000/24h identifies, but a resume does not). This PR fixes this, instead closing with a `1012` (service restart) close code, which from some discussion on the API server seems to allow resumes.
This adds a new method `CloseWithCode`, which I propose makes sense to be exported as although close codes may seem more of an internal concern, with the API exposing an implementation detail of substantial differences in close codes, users of the library should be able …

Allow resume on reconnect

---

wsapi.go

This PR is in support of Issue https://github.com/bwmarrin/discordgo/issues/754.

Change log level for websocket connection failure from warning to error

---

README.md
discord.go
docs/GettingStarted.md
docs/index.md
endpoints.go
event.go
examples/appmaker/README.md
restapi.go
wsapi.go

- Changed domain from `discordapp.com` to `discord.com` in all locations besides CDN links, to reflect the new Discord changes that will be mandatory on November 7th

Changed domain from `discordapp.com` to `discord.com`

---

README.md
docs/GettingStarted.md
docs/index.md
endpoints.go
event.go
examples/appmaker/README.md
restapi.go
wsapi.go

Reverts bwmarrin/discordgo#769
The rebase in this PR seems to be faulty—the second `Close` should have been `CloseWithCode`, but was not updated to reflect this.

Revert "Changed domain from `discordapp.com` to `discord.com`"

---

message.go

A recent API addition allows developers to explicitly list the mentions that should be valid in the message, allowing bots to safely send user input as a message without worrying about escaping the message (which never really worked, due to all of the internal processing Discord does on messages). This PR adds this functionality, allowing the `MessageAllowedMentions` struct to be used on complex message sends and edits, giving the developer the choice to explicitly disallow all mentions as a base and then selectively whitelist some. Existing functionality doesn't change—when this struct isn't provided, all mention types are still allowed.
Due to the complex nature of how the fields are processed on the backend I didn't attempt to explain every use-case in comments and linked to the …

Add allowed mentions functionality

---

restapi.go

According to https://discord.com/developers/docs/resources/guild#create-guild-channel, the endpoint also accepts the following fields:
- rate_limit_per_user: integer
- position: integer

Add missing fields in GuildChannelCreateData

---

util.go
util_test.go

The current utility only allows second precision and maybe to some people millisecond precision will come in handy since Discord timestamps are in milliseconds.

Adding millisecond precision to SnowflakeTimestamp utility

---

oauth2.go

This adds data about the Team owning an application (if there is a team owning the application), as well as its members

Add team data to applications

---

message.go
structs.go
util.go

Updates the golang stuct to current api documentation and adds new util

Updates API

---

restapi.go
structs.go

- Re-arrange Emoji to match docs
- Add new function `GuildEmoji` to get all the emoji part of a guild. The style of other GET functions is to pluralize the resource type, but pretty sure Emoji is used as both singular and plural form. Happy to change it to be `GuildEmojis` though.

Emoji improvements

---

endpoints.go
restapi.go
structs.go

Resolves #799 
Adds support for the following endpoints:
- `@/channels/:id/messages/:id/crosspost`: publishes a message in a news channel to followers
- `@/channels/:id/followers`: follows a news channel

Add support for news channels

---

user.go

In this pull request, I've added the `PublicFlags` field to the `User` struct as documented here:  
https://discord.com/developers/docs/resources/user#user-object-user-structure
This field holds publicly avaliable flags like some profile badges, for example the "Hype Squad" badges, the "Partner" badge or the "Verified Bot Developer" badge.
Also, I've added the flag values as constants to perform bitwise operations on user flags in an convenient way. The flag values are defined as documented here:  
https://discord.com/developers/docs/resources/user#user-object-user-flags
I've tried to adapt the code documentation from other flag and type descriptions as consistent as possible. If there is any issue with my implementation, please contact me and I will correct the issue. :)

add user public flags field and public flag consts

---

.travis.yml

Go 1.15 was released today, this PR adds basic testing for it within Travis CI as well.

Add 1.15 to CI

---

restapi.go
structs.go

Currently, as far as I know, there is no support for muting or deafening a user (when they are in the voice channel). I've added support for that in this PR.
As a note, `GuildMemberNickname` is still using the old code because of the `/guilds/{guild.id}/members/@me/nick` endpoint. 
On top of that, the `GuildMemberMove` command is also not using `GuildMemberEditComplex` because Discord requires the JSON request value for the `channel_id` key when removing a user to be `null` (if you want to disconnect the user), in Go, this is represented as `nil` and would be omitted by the default JSON marshaller. As a result, if `GuildMemberEditComplex` also attempted to support `ChannelID` modifications, then every change would disconnect the user unintentionally, so I omitted that functionality.
This …

Add GuildMemberEditComplex for Guild Member Mute/Deaf Edit Support

---

structs.go

It works
```go
hooks, _ := session.GuildWebhooks(guild)
for _, wh := range hooks {
fmt.Printf("webhook: %+v\n", *wh)
}
```
```
webhook: {ID:529729350946258954 Type:1 GuildID:315277951597936640 ChannelID:316038111811600387 User:qaisjp#7247 Name:matterbridge Avatar: Token:REMOVED ApplicationID:}
webhook: {ID:774818597741658172 Type:1 GuildID:315277951597936640 ChannelID:697038282701406298 User:Bridge#6643 Name:(auto-prod2) 2:12:28AM Avatar: Token:REMOVED ApplicationID:315280226936422400}
```

Add ApplicationID to Webhook

---

events.go
state.go

Similar to MessageUpdate, this change allows tracking which voice channel a user left from.
This uses the existing VoiceState tracker to include the previous VoiceState as part of the VoiceStateUpdate event.

Add previous state to VoiceStateUpdate event (#823)

---

message.go
restapi.go

Added the ability to send messages with a response (replying to another message). According to the `message_reference` field in API
https://discord.com/developers/docs/resources/channel#create-message-params
Code example:
```go
session.ChannelMessageSendComplex(channelID, &discordgo.MessageSend{
Content:   "Test",
Reference: message.Reference(),
})
```
Or:
```go
session.ChannelMessageSendReply(channelID, "Test", message.Reference())
```

Add support for sending message reply

---

restapi.go
structs.go

I added UnknownBan code to error codes in structs.go and also I made GuildBan method, so we can now get user's ban in a guild.

GuildBan method and UnknownBan error code addition

---

message.go

Direct Messages do not have the **guild_id** field for Message Referencing / the new Reply feature.
Instead it is only **message_id** and **guild_id**

Add omitempty to MessageReference's GuildID field

---

restapi.go

Addresses https://github.com/bwmarrin/discordgo/issues/860
Using the test code referenced in that issue produces the following (expected) logs:
```
=== RUN   TestRateLimitEvent
2020/12/30 13:54:06 [DG2] restapi.go:157:RequestWithLockedBucket() Rate Limiting https://discord.com/api/v6/channels/<redacted>/messages, retry in 4873
2020/12/30 13:54:06 Rate limit event triggered
2020/12/30 13:54:06 You are being rate limited.
2020/12/30 13:54:06 [DG2] restapi.go:157:RequestWithLockedBucket() Rate Limiting https://discord.com/api/v6/channels/<redacted>/messages, retry in 4856
2020/12/30 13:54:06 Rate limit event triggered
2020/12/30 13:54:06 You are being rate limited.
```

Fix invalid RateLimit event type

---

interactions.go
interactions_test.go

i had previously written a small lib to do this: [bsdlp/discord-interactions-go](https://github.com/bsdlp/discord-interactions-go), and this is basically copypasta from there.
https://discord.com/developers/docs/interactions/slash-commands#security-and-authorization

implement interaction request signing verification

---

discord.go
discord_test.go
endpoints.go
events.go
examples/airhorn/main.go
examples/pingpong/main.go
examples/voice_receive/main.go
message.go
ratelimit.go
ratelimit_test.go
restapi.go
state.go
structs.go
wsapi.go

Hi all!
I'm currently in the process of implementing API version 8 support; there was a previous PR, but it seems to have stalled out (with the user contributing having their account vanish). I've started an implementation on the `v8` branch, and would appreciate some review on it before we go ahead and merge!
There are some breaking changes: the `Game` struct is completely gone (the API doesn't have any such concept anymore), and `UpdateStatus` was changed to `UpdateGameStatus` to better reflect the true meaning of it now that games don't have elevated status; presences no longer contain information about nicknames and roles, which are now relegated to members; permissions are now represented throughout the library by `int64` rather than `int` now that they can go above 31 bits; …

Switch library to API version v8

---

restapi.go

Should not the set role/channel permissions methods also take in int64s?

Set channel and role edit perms to int64

---

examples/slash_commands/main.go

This fixes a bug in the slash commands example that causes an out-of-range error.

Fix slash commands example bug

---

structs.go

Half of what i mentioned in #904, adds in the 4 missing permissions constants, specifically:
- `1 << _9` PermissionVoiceStreamVideo
- `1 << 19` PermissionViewGuildInsights
- `1 << 31` PermissionUseSlashCommands
- `1 << 32` PermissionRequestToSpeak
to quote from the issue
> (the latter 2 are not currently in the official documentation, and the last one was only added within the past week, but being they are launched features i don't think they'll see any sudden changes at this point and are probably safe to add, and the former 2 have been around for awhile and really shouldn't be missing)
Nothing else, just adds those 4 constants

Add in some missing permission constants

---

go.mod
go.sum

This addresses a [DoS in gorilla/websocket](https://github.com/gorilla/websocket/security/advisories/GHSA-jf24-p9p9-4rjh). Exploitation appears to require that Discord be malicious,which is very low risk, but it's probably worth closing off regardless.

Update gorilla to 1.4.2

---

examples/slash_commands/main.go

Been using the _slash_commands/main.go_ example. Very helpful! Figured I'd give back with a handful of grammatical and spelling improvements.
Also I'm not sure if this is the appropriate place to bring this up or trigger some sort of change, but if you `go get github.com/bwmarrin/discordgo` and try to build this example it will fail.
The solution was to `require github.com/bwmarrin/discordgo v0.23.3-0.20210327033043-f637c37ba2f0` to use the latest version of `master`. Sounds like this won't be an issue when the next release comes.
Thanks Pedro Pessoa#8177 on discord for the help with that!

slash_commands example spelling & grammar

---

examples/slash_commands/main.go
interactions.go
structs.go
wsapi.go

Fixed all the misspells Go Report Card found except "themselvs" which is not in the code anymore.

Fix all the typos that goreportcard detected.

---

examples/slash_commands/main.go
interactions.go

~~These types were not registering as deprecated in GoLand. I updated them so that they would be recognized as deprecated.~~
Remove deprecated types as stated by the previous comments.
Relevant discord documentation: https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactioncallbacktype

Remove deprecated response types

---

.travis.yml
go.mod
go.sum
restapi.go
restapi_test.go

Update unmarshal function to wrap ErrJSONUnmarshal and return specific error message.
Requires at least Go 1.13.
Resolves #923

Update unmarshal function to wrap ErrJSONUnmarshal. Requires at least Go 1.13.

---

examples/dm_pingpong/README.md
examples/dm_pingpong/main.go

This PR adds an example on sending direct messages as it's a frequently asked question on the Discord Gophers server.
The example sends a "Pong" response through DM when a user sends "ping" in any channel the bot has the permission to see.
The example is simply adopted from the ping pong example with minor changes to respond through DM.

Add ping pong example for direct messages

---

README.md
user.go

1. Updated links that used `http` to now use `https`
* At least on my browser the report card image was broken. I replaced the image with the markdown generated on the [report](https://goreportcard.com/report/github.com/bwmarrin/discordgo).
2. Updated the Discord invites to use the vanity URL.
3. Ran `go fmt` 
* Let me know if you want me to cherry-pick this change into a separate PR. (Or if you want to just push it yourself)
[Result of the README changes](https://github.com/jolheiser/discordgo/blob/b3bec7210c234808b099c3a01ba7872bd254538d/README.md)

README updates

---

user.go

Only UserFlagDiscordEmployee had type UserFlags. All other constants
defined in the same block were untyped integer constants.
This change makes all UserFlags constants have type UserFlags. The
primary impact is that godoc and pkg.go.dev should render these
constants under the documentation for UserFlags, rather than under
package-level constants.

fix UserFlags constant types

---

examples/slash_commands/main.go
interactions.go
restapi.go
util.go
webhook.go

Webhook edits and as a result interaction followups support uploading files
https://discord.com/developers/docs/resources/webhook#edit-webhook-message
While not documented it is also possible to include files in slash command responses
This implements the same functionality as https://github.com/bwmarrin/discordgo/pull/913. and that pr may be closed if this one is approved.

support allowing webhook edits with files, and responding to interactions with files

---

examples/context_menus/main.go
interactions.go
message.go
webhook.go

Lo and behold, context menus are coming.

Context menus

---

structs.go

Current GatewayBotResponse struct is missing the information required for max concurrency sharding: https://discord.com/developers/docs/topics/gateway#get-gateway-bot-json-response

Add SessionStartLimit to GatewayBotResponse struct

---

events.go
state.go
structs.go

Added functionality to be able to access a Guild copy in the GuildDelete event, just like with MessageDelete.

Add BeforeDelete to GuildDelete struct

---

examples/autocomplete/main.go
interactions.go

This PR contains implementation of necessary interaction types and payloads for newly introduced option auto completion for slash commands. 
[WIP docs and showcase](https://devsnek.notion.site/devsnek/Application-Command-Option-Autocomplete-Interactions-dacc980320c948768cec5ae3a96a5886) if anyone is interested

Slash commands options auto completion

---

structs.go

Added missing audit logs actions and keys, also reordered them to follow the order in the discord docs (https://discord.com/developers/docs/resources/audit-log)
For the audit log change key, in the discord docs the table has 4 columns (name, object changed, type, description).
To follow that, I decided to go with this "syntax":
`AuditLogChangeKeyAfkChannelID               AuditLogChangeKey = "afk_channel_id"                // afk channel changed (snowflake) - guild`
`// Description (type) - object changed`. Let me know what you think of this.

Update auditlog keys and actions

---

interactions.go

This PR implements newly added (https://github.com/discord/discord-api-docs/pull/4253) attachment option for application commands.

Application commands: attachment option

---

message.go
structs.go

This PR add stickers field to Guild, and move some Sticker code to structs.go.
Ref: [https://discord.com/developers/docs/resources/guild](https://discord.com/developers/docs/resources/guild)

Add get guild stickers support

---

components.go

[Discord API docs](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure) show disabled as an option for SelectMenu. Add that prop

Add disable prop to Select Menu

---

eventhandlers.go
events.go
message.go
oauth2.go
structs.go

Fixes #1104 
See [this PR](https://github.com/discordeno/discordeno/issues/640) and the linked one for the change of target_user_type -> target_type
I moved the Application struct, and i noticed that there were some fields not on the discord documentation, nor in the git history of the docs repo. Does the oauth2/applications/<id> endpoint still exist? all i can find is [this](https://discord.com/developers/docs/topics/oauth2#get-current-bot-application-information).

Add Invite Create/Delete

---

endpoints.go
restapi.go
structs.go
user.go
util.go

Fixes https://github.com/bwmarrin/discordgo/issues/965
This PR adds support for the Guild-specific member avatar, if any.
To follow the same pattern as `*User.AvatarURL`, also add the same method for `*Member.AvatarURL` , and create an util method `avatarURL` to handle both.
Also, set the `*Member.GuildID` after the `GuildMember` requests, as this is not included with the returned object.
I have tested these changes with my own bot

Add Guild Member avatar

---

message.go

This pr adds the interaction field to the message struct 
https://discord.com/developers/docs/resources/channel#message-object-message-structure
there is another pr for this which seems to be dead and is wrongly implemented https://github.com/bwmarrin/discordgo/pull/929

add interaction field to message struct

---

endpoints.go
structs.go
user.go
util.go

I will add Guild Member Cover & Accent Color support to the library 
Resolve #1093

feat: Add Guild Member Cover & Accent Color support

---

restapi.go

The comment for the InteractionRespond method mentions an appID despite the lack of an appID parameter. Likely copy paste. This change removes mention of the appID.

Removed appID comment from InteractionRespond method which does not have this parameter

---

components.go
interactions.go
message.go

Some context: https://discord.com/channels/613425648685547541/697489244649816084/946485657184911411

Remove `omitempty` for `Embeds`

---

structs.go

Adds a couple of permission constants that were missing, specifically:
- Use Activities / 0x8000000000
- Manage Events / 0x200000000
- Use External Stickers / 0x2000000000

Add missing permission constants (UseActivities, ManageEvents, UseExternalStickers)

---

restapi.go

This message was happening a lot here, the thing is that when successfully read, the ioutil closes the body. So it will always trigger an error.
Also I think that message was mean't to be enabled only in debug. So I added the debug flag check :D

fix: Fix debug message printing when debug is disabled.

---

examples/slash_commands/main.go

https://github.com/bwmarrin/discordgo/issues/1126 [Method 3](https://github.com/bwmarrin/discordgo/issues/1126#issuecomment-1062543250)
The resulting example output:

Slash commands example: parse options into a map

---

restapi.go
structs.go

When editing a guild member, you can do much more than just update their roles, i.e. their nickname
[Discord docs](https://discord.com/developers/docs/resources/guild#modify-guild-member)
This change the method signature to expose a payload struct devs can use to set what they want to change on the member. We ommit any value from the future json payload if it was not set

Payload for member edit

---

restapi.go

Since i ran into the same issue today, the documentation for MessageReactionAdd should be improved, thanks to #750

Add example of emojiID to MessageReactionAdd

---

structs.go

Fix RateLimitPerUser on ChannelEdit

---

restapi.go

This PR implements [`GuildEmoji`](https://discord.com/developers/docs/resources/emoji#get-guild-emoji) REST method.

Implement GuildEmoji

---

restapi.go
state.go

I pulled latest and opened it up in VS Code, and there were 3 `ineffectual assignment to err (ineffassign)` errors from the `go-golangci-lint` linter, found in `restapi.go` on line 2548, `state.go` on line 857, and `state.go` on line 873.
The "ineffectual assignment to err" means that the code is assigning a value to a variable `err`, but then the variable goes out of scope without ever being used. Looking at the code, all 3 cases are due to the `:=` assignment operator creating a second `err` variable in the local scope, instead of re-using the `err` that is a named return value.
More info: [Golang Variable Shadowing](https://rpeshkov.net/blog/golang-variable-shadowing/).

fix shadowed variables that were preventing errors from being returned properly

---

discord.go
restapi.go
structs.go

Some requests are time sensitive and become stale if not completed quickly. It's better to let the library user choose how to handle a rate limit being exceeded in those cases. `ShouldRetryOnRateLimit` is a session option which disables automatic retry and instead returns an error the user can use to handle retry manually. 
Closes #1011.

Add option to disable rate-limited request retry

---

endpoints.go
eventhandlers.go
events.go
examples/stage_instance/main.go
restapi.go
structs.go

**Describe task**
Add the support of Stage Instance to the discordgo library.
**Notes**
I also add the link between Stage Channel, Stage Instance and Scheduled Events
*The RestAPI endpoint is not tested for the moment, the stage instance needs to have a stage channel setup and user presence in channel to be test*
Resolves #903

feat: Add support of Stage Instance RestAPI and Events

---

restapi.go

Changes function to not omit empty role information. This allows for properly resetting the roles of an emoji, otherwise it appears to be presently impossible to reset the roles (without including a role ID in the edit request).

Modify GuildEmojiEdit function of restapi.go

---

events.go
wsapi.go

I'm not sure if the "guild_id" field should be an array because according to the [documentation](https://discord.com/developers/docs/topics/gateway#request-guild-members-guild-request-members-structure), it should be a string. The endpoint accepts both array and string without errors.

Updated RequestGuildMembers method and GuildMembersChunk event struct

---

components.go
restapi.go
structs.go
util.go

This PR adds functionality for replacing default marshal and unmarshal functions with custom ones.
Remake of #959

Custom JSON marshal/unmarshal functions

---

restapi.go

This PR implements `InviteComplex`.
`InviteComplex` is a function which allows to specify which fields should be provided by the `GET /invites/:inviteID` endpoint.
Such parameters are:
- approximate member counts
- invite expiration time
- linked scheduled event id, if there is any

Add InviteComplex

---

eventhandlers.go
events.go
examples/slash_commands/main.go
interactions.go
restapi.go
structs.go

Implements permissions v2 API for application commands
ref: https://github.com/discord/discord-api-docs/pull/4830

Application commands: Permissions v2

---

structs.go

AuditLogActionApplicationCommandPermissionUpdate was just of type `int` instead of `AuditLogAction`

fix: type of AuditLogActionApplicationCommandPermissionUpdate

---

message.go

This is needed to reply without mentions.
https://discord.com/developers/docs/resources/channel#allowed-mentions-object

Add replied_user to MessageAllowedMentions

---

README.md

1. Remove the Travis Badge as that pipeline doesn't exist anymore, replace it with the Github Actions CI workflow badge
2.  Remove the Go Walker link, Go Walker doesn't seem to work anymore

Remove broken links from README

---

examples/slash_commands/main.go
webhook.go

These need to be pointers to allow removing embeds, content, and components from an existing message.
omitempty was added to components to allow keeping the existing components on a message when calling WebhookEdit

make WebhookEdit fields pointers

---

voice.go

Occasionally it causes panic when secretbox.open failed.
Below in the code we read `extlen := binary.BigEndian.Uint16(p.Opus[2:4])`
But opus can be nil.
I encountered this problem myself.

fix: check if opus created

---

examples/components/main.go
examples/context_menus/main.go
examples/modals/main.go
examples/slash_commands/main.go
interactions.go
webhook.go

According to the Discord documentation, the values for `InteractionResponseData.Flags` and `WebhookParams.Flags` are just a subset of the standard `MessageFlags`:
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-messages
https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params
https://discord.com/developers/docs/resources/channel#message-object-message-flags
So use that type instead and put a note indicating the valid subset of flags for each of them. 
This is a breaking change, as the type is changing, so any code that is setting those flags will need to change to use the `MessageFlags` values instead, as it was done in the examples.

Use `MessageFlags` as the type for `Flags` in `InteractionResponseData` and `WebhookParams`  

---

examples/voice_receive/main.go

examples/voice_receive cannot be built.
MakeIntent did not have been used to initialize Intents.
```
./discordgo/examples/voice_receive
$ go build  
./main.go:78:21: cannot use discordgo.IntentsGuildVoiceStates (type discordgo.Intent) as type *discordgo.Intent in assignment
```

Fix build error of examples/voice_receive

---

structs.go

Updating the `VoiceState` struct with new fields as shown in [Discord docs for Voice State](https://discord.com/developers/docs/resources/voice#voice-state-object-voice-state-structure), and arranged them in the same order as the docs

Add missing fields to VoiceState struct

---

.fleet/settings.json
structs.go

This is a fix to PR https://github.com/bwmarrin/discordgo/pull/1091. It seems that the ``UsageCount`` field was incorrectly set to a string instead of a int. This PR has been made to fix this. I've tested this fix on my own machine.
Relevant Documentation: https://discord.com/developers/docs/resources/guild-template

Fix GuildTemplate struct and documentation

---

interactions.go

This PR implements newly introduced `app_permissions` field for `Interaction`.
Useful links:
- [Changelog](https://discord.com/developers/docs/change-log#calculated-permissions-in-interaction-payloads)
- [Documentation](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure)
- https://github.com/discord/discord-api-docs/pull/5131

Interaction application permissions

---

interactions.go

Add missing `guild_id` to `ApplicationCommand` structure. [Documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure)

Add GuildID field to ApplicationCommand

---

endpoints.go
eventhandlers.go
events.go
examples/auto_moderation/main.go
restapi.go
structs.go

This PR implements newly added auto moderation API and adds a new example on how to use it.
* [Documentation](https://discord.dev/resources/auto-moderation)
* https://github.com/discord/discord-api-docs/pull/4860

Auto moderation

---

interactions.go

Implement newly added `min_length` and `max_length` fields for string option type.
- [Documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure)
- [Changelog](https://discord.com/developers/docs/change-log#min-and-max-length-for-command-options)
- https://github.com/discord/discord-api-docs/pull/5143

Application command options: min and max length

---

discord.go
logging.go
state.go
structs.go

This fixes the name of `InviteTargetEmbeddedApplication` (previously `InviteTargetEmbeddedAppliction`)
as well as some minor changes to random mistyped comments.

fix typo in InviteTargetEmbeddedApplication

---

examples/threads/main.go
structs.go

Setting e.g. `ChannelEdit.Archived = false` is currently not possible as Go will treat a `false` value as empty and will omit the `archived` property from the resulting JSON object. The same goes for `Locked`, `NSFW` and `Invitable`.

Allow setting bool fields of `ChannelEdit` to false

---

message.go

[Per documentation](https://discord.com/developers/docs/resources/channel#message-types-replies) channel_id and guild_id are not required. GuildID is already marked as omitempty but ChannelId can be as well.

Add omitempty to channel_id in MessageReference struct

---

discord.go
structs.go
wsapi.go

A little attempt to make this pull request.
Why would I need such an update? For example, if I would be able to pass custom `Dialer`, then I could use proxy ([click](https://stackoverflow.com/questions/33585587/creating-a-go-socks5-client)).
```go
dialSocksProxy, _:= proxy.SOCKS5("tcp", "proxy_ip", nil, proxy.Direct)
s, _:= discordgo.New("token")
s.Dialer = &websocket.Dialer{Dial: dialSocksProxy.Dial}
```
Sorry if I'm wrong. I'll be very happy to hear where exactly I made a mistake, if there's one.

Add `Dialer` property to `Session`

---

endpoints.go
restapi.go

This PR implements the rest method to [Get Current User Guild Member](https://discord.com/developers/docs/resources/user#get-current-user-guild-member). I didn't find an open issue or discussion for this, but it is relatively straightforward to implement so I hope it's okay.

feat: add UserGuildMember

---

voice.go

Use `Session.Dialer` for creation of websocket connections to voice endpoints.
This PR originates from https://github.com/bwmarrin/discordgo/pull/1179#discussion_r897291113 and was created since the push permissions were disabled on the branch.

Use Dialer for Voice connections

---

structs.go

GuildFeatures added to UserGuild

---

structs.go

This PR adds the following fields to the GuildMemberParams.
- `channel_id`
- `mute`
- `deaf`
- `communication_disabled_until`

Add missing fields to GuildMemberParams

---

eventhandlers.go
events.go
structs.go

After #1078 was merged, there were still some undocumented structs and fields present.
This PR removes them.

Remove remaining undocumented structs and fields

---

restapi.go
structs.go

We have been thinking on how to improve developer experience with the library and clean up some stuff. 
One of the aspects that came to our attention is REST methods. Currently we don't have a consistent naming and signature style. 
This PR addresses this problem.
It refactors REST methods to use structs where possible and removes some of the unnecessary helper methods.
**This only affects older functions** , functions that came after `v0.24.0` already are following this design.
Here's how the usage will change:
```diff
// Change role name.
- s.GuildRoleEdit(guildID, roleID, "new name", 0xFFFFFF, true, 0x0, true)
+ s.GuildRoleEdit(guildID, roleID, &discordgo.RoleData {
+    Name: "new name",
+ })
// Change member's roles and nickname.
- s.GuildMemberEdit(guildID, memberID, roles)
- …
```

REST methods cleanup

---

restapi.go

Make `g` parameter of `GuildEdit` a pointer.

Use pointer for `GuildParams` in `GuildEdit`

---

restapi.go
structs.go

Implementation of newly added forum channels.
- [Documentation](https://discord.com/developers/docs/topics/threads#forums)
- [Changelog](https://discord.com/developers/docs/change-log#forum-channels-release)
- https://github.com/discord/discord-api-docs/pull/4761

Forum channels

---

interactions.go

If i’m not mistaken, the gID parameter of `RoleValue(s *Session, gID string)` line 465 of `interactions.go` corresponds to the guild ID.
The gID parameter was passed to State.Role as roleID and the roleID was passed as guildID.
Inverting the arguments should fix the issue.

fix(interactions): incorrect call of State.Role in RoleValue()

---

structs.go

Seems like the types of the enum values of `GuildScheduledEventStatus` and
`GuildScheduledEventEntityType` were overlooked and were left as `int`,
resulting in the need to cast them each time you want to use them.

fix(structs): fix type of `GuildScheduledEvent*` enum values

---

util.go

Currently `MultipartBodyWithJSON` uses `file<index>` format for the `name` of the form field for files. However this format is not correct, according to the [documentation](https://discord.com/developers/docs/reference#uploading-files). The correct format is `files[<index>]`.
The implementation was working all that time, because all the endpoints with support of attachments append them automatically and you do not need to reference them, however when you would try to, you would just get an "Unknown attachment" error. 
This PR should fix this problem.
Initially I discovered this when I was performing manual tests on #1253.

fix(MultipartBodyWithJSON): form file field name format

---

message.go
restapi.go

This PR adds the ability to edit the attachments of a message, following the discord API.

Add files to MessageEdit

---

message.go

Remove omitempty from Name/value since the Discord API requires both to be submitted.
https://discord.com/developers/docs/resources/channel#embed-object
Fixes: #726

fix: remove embedfield omitempty

---

voice.go

Same as #1230 .
Sorry, I made a mistake and closed it.
#1166 has avoid panic but cause a silent fail.
This fixes it.
Broken packet should be ignored and continue to next packet.
This goroutine should not exit until close.

Continue to next packet if received broken packet

---

events.go
state.go

Add `Shard` and `Application` fields to `Ready` event struct.

Add missing fields to Ready

---

structs.go

Fix EmojiRegex to accept emojis with ids up to 20 characters long

EmojiRegex: emojis with longer ids

---

wsapi.go

This commit adds the UpdateWatchStatus method that can be used to set discords Watch status (see https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum).

feat: add UpdateWatchStatus function

---

voice.go

Fixes #849.
When the bot was moved to another vc, the connection was disconnected with `4014 Disconnected`.
* https://github.com/Rapptz/discord.py/issues/5904
* https://github.com/discord/discord-api-docs/issues/2450
* https://github.com/discordjs/guide/blob/main/guide/voice/voice-connections.md#handling-disconnects
Then, `VOICE_SERVER_UPDATE` is received after `4014 Disconnected`.
```
2022/10/30 14:47:23 [DG2] voice.go:356:wsListen() received 4014 manual disconnection
2022/10/30 14:47:23 [DG2] voice.go:167:Close() called
2022/10/30 14:47:23 [DG2] voice.go:176:Close() closing v.close
2022/10/30 14:47:23 [DG2] voice.go:182:Close() closing udp
2022/10/30 14:47:23 [DG3] wsapi.go:547:onEvent() Op: 0, Seq: 6, Type: VOICE_STATE_UPDATE, Data: [hidden]
2022/10/30 14:47:23 [DG3] …
```

Fix the problem of reconnecting when moved to another VC

---

structs.go

I've updated the `GuildParams` struct to be complient with the [`Modify Guild`](https://discord.com/developers/docs/resources/guild#modify-guild) payload as described in the Discord API docs. Therefore, I've also added the two System Channel Flags `SUPPRESS_GUILD_REMINDER_NOTIFICATIONS` and `SUPPRESS_JOIN_NOTIFICATION_REPLIES` to the `SystemChannelFlag` constants.
This pull request should fix issue #994.

Complement `GuildParams` struct to comply with Discord's API

---

structs.go

Add AllowList and MentionTotalLimit to AutoMod as shown in docs below.
https://discord.com/developers/docs/resources/auto-moderation#auto-moderation-rule-object-trigger-metadata

Automod trigger metadata update

---

events.go
state.go

Hey! I'm currently using this package in a personal project and wanted to track member role changes.
Since the old state of the Member is currently not part of the GuildMemberUpdate, I've simply added it similar to how it was done for other events like ThreadUpdate or MessageUpdate.
Fixes #1200

Provide previous Member state for GuildMemberUpdate events

---

state.go
structs.go

Add the ClientStatus struct to the PresenceUpdate struct based on the document below.
https://discord.com/developers/docs/topics/gateway-events#presence-update-presence-update-event-fields

Add Presence ClientStatus

---

structs.go

Add some settings of forum channel as shown docs.
https://discord.com/developers/docs/change-log#add-default-layout-setting-for-forum-channels
https://discord.com/developers/docs/change-log#default-sort-order-for-forum-channels
https://discord.com/developers/docs/resources/channel#channel-object-channel-structure

Add Forum settings to Channel struct

---

voice.go

Update format of the UDP handshake when performing IP discovery.
```diff
+ direction (2 bytes, 1 - send, 2 - recv)
+ length (2 bytes, 70)
ssrc (4 bytes)
- ip (16 bytes)
+ ip (64 bytes, null terminated)
port (2 bytes)
```

74 byte handshake

---

restapi.go
restapi_test.go

fix: WithContext had no effect

---

structs.go

The `Flags` field was being incorrectly de/serialized as `"Flags"`.
ThreadMember spec: https://discord.com/developers/docs/resources/channel#thread-member-object
I caught this with the `musttag` linter, so I went ahead and added it to the linter config.

fix: ThreadMember flags not serialized

---

interactions.go

Resolves this issue. #1359 
Reference: https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data

Add CommandType to ApplicationCommandInteractionData

---

structs.go

https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-events
https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-optional-audit-entry-info

feat(auditlog): add auto moderation actions and options

---

message.go

https://discord.com/developers/docs/resources/channel#message-reference-object
I wanted to make this a parameter of the `Reference` function where you can pass in false if needed. Go doesn't support default parameter values so I don't know how I should go about doing that. Any pointer are appreciated.

Add fail_if_not_exists to MessageReference

---

restapi.go

[Delete Guild returns `204` (No Content), with no content.](https://discord.com/developers/docs/resources/guild#delete-guild). This PR updates the `GuildDelete` method to not attempt an unmarshal, and only return an error.
Extract from a recent test run:
```
2023/02/12 00:13:08 API REQUEST   DELETE :: https://discord.com/api/v9/guilds/***
2023/02/12 00:13:08 API REQUEST  PAYLOAD :: []
2023/02/12 00:13:08 API REQUEST   HEADER :: [Authorization] = [Bot ***]
2023/02/12 00:13:08 API REQUEST   HEADER :: [User-Agent] = [DiscordBot (https://github.com/bwmarrin/discordgo, v0.25.0)]
2023/02/12 00:13:09 API RESPONSE  STATUS :: 204 No Content
2023/02/12 00:13:09 API RESPONSE  HEADER :: [Date] = [Sun, 12 Feb 2023 00:13:08 GMT]
2023/02/12 00:13:09 API RESPONSE  HEADER :: [X-Ratelimit-Remaining] = [3] …
```

Remove returned guild from GuildDelete

---

structs.go

Put into a seperate PR as per #1371
I added it above the moderator fields because that is the order they were added to the api.

feat(auditlog): add application_id to AuditLogOptions

---

discord.go
structs.go
wsapi.go

This PR adds a flag in order to prevent voice reconnect on session reconnect. The default value is set to `true` so it should not affect the initial behaviour.
Resolves #1349

Add toggle for voice reconnect on session reconnect

---

endpoints.go

`EndpointGuilds` already has a slash at the end so we end up with `/guilds//templates` which is not ideal. The Discord API ignores the double slash but if you are using some kind of proxy it doesn't work.

Remove remove duplicated slash in template endpoint

---

structs.go

Perhaps they had this value previously but that is not the case right now.
Per the docs at https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-optional-audit-entry-info
> type | Type of overwritten entity - role ("0") or member ("1")
role_name makes that even more clearer:
> role_name | Name of the role if type is "0" (not present if type is "1")

fix(auditlog): Use correct values for AuditLogOptionsType

---

voice.go

Closes https://github.com/bwmarrin/discordgo/issues/829
When checking the Voice Session ID in `VoiceConnection.open()`, the sessionID is populated asynchronously when websocket messages come in, see [wsapi.go](https://github.com/bwmarrin/discordgo/blob/master/wsapi.go#L736C19-L736C19). 
However, `open()` still holds the lock on the session, so the ID can never be populated, and we loop and accomplish nothing until releasing the lock upon exiting the function. 
This PR addresses this deadlock bug by momentarily releasing the lock anytime the process sleeps, allowing other processes to populate the sessionID appropriately - while not sacrificing concurrency safety by releasing the lock entirely.

Fix session ID deadlockwhen opening a VoiceConnection

---

message.go

https://discord.com/developers/docs/resources/channel#message-object-message-flags

Add new MessageFlags

---

message.go

https://discord.com/developers/docs/resources/channel#create-message

feat(MessageSend): add flags

---

webhook.go

https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params

Add missing `thread_name` field for creating forum posts with webhooks

---

user.go

I noticed the PremiumType field on the User struct has no specific type (and instead has type int).
Because of this, I had to define the type/consts myself or use magic numbers. I think it should be added in the library, as other fields do have their own types (like User.PublicFlags).
See the Discord documentation at https://discord.com/developers/docs/resources/user#user-object-premium-types

feat(user): Add UserPremiumType type

---

user.go

Added following UserFlags:
- BOT_HTTP_INTERACTIONS
- SPAMMER
- ACTIVE_DEVELOPER
The spammer flag is currently undocumented by discord, but seen in other discord libraries.

feat(UserFlags): add BotHTTPInteractions and ActiveDeveloper

---

components.go

Implement `DefaultValues` for `SelectMenu` component.
See https://github.com/discord/discord-api-docs/pull/6442 for more info.

feat(SelectMenu): default values

---

restapi.go
structs.go

Apply DiscordAPI changes
https://discord.com/developers/docs/change-log#thread-member-details-and-pagination

Add Member field to ThreadMember struct

---

structs.go
structs_test.go

This PR adds a simple helper on the `Member` struct to retrieve a member display name on the server, by either using the member nick if one is set, or the profile display name (called `GlobalName` in the API)
Would love to see this as part of https://github.com/bwmarrin/discordgo/milestone/25 :)

feat(member): add helper function for display name

---

interactions.go
webhook.go

Add Attachment options to interactions so that editing uploaded files is possible.
Behavior documented here: https://discord.com/developers/docs/resources/webhook#edit-webhook-message

Add Attachment options to interactions

---

endpoints.go
restapi.go
structs.go

Adds support for inspecting the onboarding configuration of a guild.
https://discord.com/developers/docs/resources/guild#guild-onboarding-object
I want to know which roles are assignable by users through onboarding, which this is needed for.

feat(guild): implement onboarding

---

endpoints.go
structs.go

This partially addresses #1316 by adding support for the fields mentioned in this PR's title. 
I tested this on a server with role icons and emoji and encountered no issues.

Added support for the icon and unicode_emoji role struct fields

---

components.go
examples/components/main.go

fix(buttons): omit empty emoji field

---

components.go
examples/components/main.go

The emoji validation fixed in pr #1475 did not cover another emoji validation case with the `SelectMenuOption`. This fixes forward this breaking change from the API -
Example response from using a SelectMenuOption:
```
HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"components": {"0": {"components": {"0": {"options": {"0": {"emoji": {"name": {"_errors": [{"code": "BUTTON_COMPONENT_INVALID_EMOJI", "message": "Invalid emoji"}]}}}}}}}}}}
```

Modify SelectMenuOption Emoji field to omitempty

---

message.go
restapi.go

A while ago there was a small discussion on this topic in discord [down from this message](https://discord.com/channels/118456055842734083/155361364909621248/1172388479964028959)
Implemented as was described(at least I think that's what was meant about converting slices to slices of pointers), here's a recording of it working
Snippet with example of code that's used for suppression.
```go
func MessageUpdate(s *discordgo.Session, m *discordgo.MessageUpdate) {
if len(m.Embeds) > 0 {
messageEdit := discordgo.NewMessageEdit(m.ChannelID, m.ID)
messageEdit.Flags = discordgo.MessageFlagsSuppressEmbeds
s.ChannelMessageEditComplex(messageEdit)
s.ChannelMessageSend(m.ChannelID, "Suppressed embed")
}
}
```

fix(message)!: omit empty Components and Embeds

---

restapi.go

Return `*Webhook` for `WebhookEdit` and `WebhookEditWithToken`.
Fixes #1495

fix!: return Webhook struct from WebhookEdit and WebhookEditWithToken

---

locales.go

Add "Spanish LATAM" to supported locales.
https://github.com/discord/discord-api-docs/pull/6577

feat(locales): add Spanish LATAM

---

message.go
structs.go

https://discord.com/developers/docs/resources/channel#message-object
https://discord.com/developers/docs/resources/sticker#sticker-item-object
There exists a property called `stickers` that contain the full sticker information but that is deprecated and not part of the struct here.

feat(message)!: use partial sticker objects

---

endpoints.go
structs.go

Depends on #1334
https://discord.com/developers/docs/topics/permissions#role-object-role-flags
A better solution to what I was doing in my onboarding pr, wasn't documented at the time though.
I also thought about adding the `tags` field as per #1316 but that has weird nullable types I didn't want to bother with. The issue should also be reopened as the PR doesn't address it fully and isn't merged.

feat(role): add flags

---

restapi.go
restapi_test.go
structs.go

This PR adds support for the `with_count` query parameter on the `UserGuilds()` function. 
Additionally, the `limit` of returned guilds has been increased from 100 to 200.
Reference: https://discord.com/developers/docs/resources/user#get-current-user-guilds

feat(UserGuilds): support with_counts parameter

---

structs.go

Support the channel types 14 (GUILD_DIRECTORY) and 16 (GUILD_MEDIA)
Reference: https://discord.com/developers/docs/resources/channel#channel-object-channel-types

Add channel types `ChannelTypeGuildDirectory` and `ChannelTypeGuildMedia`

---

events.go
structs.go

Adds the field GuildID to the AuditLogEntry struct.  While not documented (https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-entry-structure) it is part of the struct sent on the wire:

feat(GuildAuditLogEntryCreate): add guild_id

---

interactions.go
message.go
structs.go

Implement [user-installable applications](https://discord.com/developers/docs/change-log#userinstallable-apps-preview),
which were recently introduced by Discord.

feat: user apps

---

examples/avatar/main.go
restapi.go

Add support for editing bot's banner using `UserUpdate`.
🚧 This PR is built upon an [yet to be documented](<https://github.com/discord/discord-api-docs/pull/6710>) feature 🚧

feat(Session.UserUpdate)!: add banner support

---

structs.go

I added the missing `custom_message` field to the AutoModerationActionMetadata.
Documented here: https://discord.com/developers/docs/resources/auto-moderation#auto-moderation-action-object-action-metadata

Add CustomMessage to AutomoderationActionMetadata

---

examples/slash_commands/main.go
structs.go

First commit makes the numbers bitflags which I find easier to parse and follows all the other flags in the repo. I also added docs for them.
Second commit adds missing flags currently documented at https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags
Third commit renames some fields to what they are now called on discords docs page.
Fourth commit adds currently undocumented flags, but there is a pending pr for those at https://github.com/discord/discord-api-docs/pull/6305

Add new permissions

---

wsapi.go

Couldn't find a way to send a raw gateway message, so added a wrapper function around `wsConn.WriteJSON`

feat: Add SendRawGatewayMessage function

---

structs.go

As documented in https://discord.com/developers/docs/resources/poll#poll-results-object-poll-results-object-structure, answer_count should be answer_counts

Fix typo in PollResults AnswerCounts json field

---

interactions.go

Add a utility get option function, it will help.

feat(interaction): Add GetOption method on Application Interaction Command

---

structs.go

Updates the `VoiceRegion` struct to export all VoiceRegion fields.
https://discord.com/developers/docs/resources/voice#voice-region-object

Add additional fields to VoiceRegion struct

---

endpoints.go
restapi.go
structs.go

This PR aims to add support for the REST points that manage Application based emojis.

Implement support for Application emojis

---

message.go
message_test.go

This PR adds the `MessageReferenceType` type to `MessageReference`s as per https://github.com/bwmarrin/discordgo/issues/1594
It also adds a `Forward` convenience method on messages to create a forward reference for messages

Add `MessageReferenceType`

---

endpoints.go
structs.go

As of july 16th 2024, member banners were added to the API. 
Ref: https://discord.com/developers/docs/change-log#guild-member-banners
This PR adds the banner field, BannerURL method, and endpoints.

feat: add guild member banners

---

eventhandlers.go
events.go
structs.go

I've implemented the Subscriptions event listener and it's now being used in the project. Please review and merge when you have a chance. Thanks.
https://discord.com/developers/docs/monetization/implementing-app-subscriptions

Implementing Subscriptions

---

structs.go

EmojiRegex uses range [A-z], which includes more characters than [A-Z] and [a-z]. Couldn't tell if this was always guaranteed to be run case insensitive, so made it [A-Za-z]

fix(EmojiRegex): A-z range 

---

structs.go
structs_test.go
user.go
user_test.go

User.GlobalName can be empty.
https://discord.com/developers/docs/resources/user#user-object-user-structure
So we need helper function to select the effective name.
This change is already mentioned at https://github.com/bwmarrin/discordgo/pull/1426#issuecomment-1687974189

feat(user): Add helper function to get effective display name

---

restapi.go

Otherwise you need to either artificially make a map[string]any from the json or duplicate
```go
if bucketID == "" {
bucketID = strings.SplitN(urlStr, "?", 2)[0]
}
return s.RequestWithLockedBucket(method, urlStr, contentType, b, s.Ratelimiter.LockBucket(bucketID), sequence, options...)
```
and I think the details of the rate limit/locking logic should stay hidden rather than duplicated in caller code

Expose s.request as s.RequestRaw so one can send JSON directly

---

webhook.go

Adds `Flags` field to `WebhookEdit`: https://discord.com/developers/docs/resources/webhook#edit-webhook-message

feat(WebhookEdit): add flags

---

components.go

fixing a typo in struct tag for Spoiler field in Thumbnail struct in `components.go` "omitemoty" -> "omitempty"

fix(Thumbnail): correct typo in JSON tag for Spoiler field

---

event.go
events.go
structs.go
wsapi.go

Implement [`resume_gateway_url`](https://discord.com/developers/docs/change-log#sessionspecific-gateway-resume-urls) functionality for the gateway.

Resume gateway url

---

structs.go

Fixed a typo in one of the comments, under the type Session code block, in the documentation. Should be "Maybe", instead of "Maye be".

chore: typo in comment under Session struct
